# Generated by Django 3.0.3 on 2020-03-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('superkey', models.CharField(default=None, max_length=100)),
                ('bill_id', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('table_no', models.CharField(default=None, max_length=50)),
            ],
            options={
                'verbose_name': 'Restaurant Bill Detail',
            },
        ),
        migrations.CreateModel(
            name='Bill_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superkey', models.CharField(default=None, max_length=100)),
                ('bill_id', models.CharField(default=None, max_length=50)),
                ('table_no', models.CharField(default=None, max_length=50)),
                ('food_id', models.CharField(default=None, max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient_Table',
            fields=[
                ('superkey', models.CharField(default=None, max_length=100)),
                ('ingredient_id', models.CharField(default=None, max_length=40, primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(default=None, max_length=100)),
                ('total', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Restaurant Store Detail',
            },
        ),
        migrations.CreateModel(
            name='Rest_Employee',
            fields=[
                ('superkey', models.CharField(default=None, max_length=100)),
                ('employee_id', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('fname', models.CharField(default=None, max_length=20)),
                ('mname', models.CharField(default=None, max_length=20, null=True)),
                ('lname', models.CharField(default=None, max_length=20)),
                ('picture', models.ImageField(blank=True, default='profile_pic/profile_picture.jpg', upload_to='profile_pic/')),
                ('work', models.CharField(default=None, max_length=50)),
                ('salary', models.IntegerField(default=0)),
                ('dob', models.DateField(default=None)),
                ('phone', models.CharField(default=None, max_length=13)),
                ('address', models.CharField(default=None, max_length=200)),
                ('state', models.CharField(default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=50)),
                ('pincode', models.CharField(default=None, max_length=10)),
                ('father_name', models.CharField(default=None, max_length=60)),
                ('father_phone', models.CharField(default=None, max_length=13, null=True)),
                ('from_date', models.DateField(default=None)),
                ('to_date', models.DateField(default=None, null=True)),
            ],
            options={
                'verbose_name': "Restaurant Employee's Detail",
            },
        ),
        migrations.CreateModel(
            name='Rest_Food',
            fields=[
                ('superkey', models.CharField(default=None, max_length=100)),
                ('food_id', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('food_name', models.CharField(default=None, max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Restaurant Meal Detail',
            },
        ),
        migrations.CreateModel(
            name='Rest_Management',
            fields=[
                ('mainkey', models.CharField(default=None, max_length=100)),
                ('superkey', models.CharField(default=None, max_length=100, unique=True)),
                ('license_no', models.CharField(default=None, max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(default=None, max_length=20, unique=True)),
                ('password', models.CharField(default=None, max_length=20)),
                ('emailid', models.EmailField(default=None, max_length=100)),
                ('phone', models.CharField(default=None, max_length=10)),
                ('rest_name', models.CharField(default=None, max_length=50)),
                ('state', models.CharField(default=None, max_length=30)),
                ('city', models.CharField(default=None, max_length=30)),
                ('pincode', models.CharField(default=None, max_length=6)),
                ('address', models.CharField(default=None, max_length=200)),
            ],
            options={
                'verbose_name': "Restaurant's Detail",
            },
        ),
    ]
