# Generated by Django 3.0.3 on 2020-03-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('superkey', models.CharField(default=None, max_length=100)),
                ('bill_no', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('room_id', models.CharField(default=None, max_length=50)),
                ('customer_id', models.CharField(default=None, max_length=100)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('type_of_work', models.CharField(default=None, max_length=60, null=True)),
                ('extra', models.PositiveIntegerField(default=0, null=True)),
                ('no_of_days', models.PositiveIntegerField(default=0)),
                ('day_out', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Hotel Bill Detail',
            },
        ),
        migrations.CreateModel(
            name='Customer_Register',
            fields=[
                ('superkey', models.CharField(default=None, max_length=100)),
                ('customer_id', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('addar_no', models.CharField(default=None, max_length=15)),
                ('room_id', models.CharField(default=None, max_length=50)),
                ('fname', models.CharField(default=None, max_length=20)),
                ('mname', models.CharField(default=None, max_length=20, null=True)),
                ('lname', models.CharField(default=None, max_length=20)),
                ('no_of_days', models.CharField(default=None, max_length=10)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(default=None, max_length=13)),
                ('address', models.CharField(default=None, max_length=200)),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('checkin_date', models.DateField(default=None)),
                ('checkout_date', models.DateField(default=None, null=True)),
            ],
            options={
                'verbose_name': "Hotel Customer's Detail",
            },
        ),
        migrations.CreateModel(
            name='Hotel_Employee_Register',
            fields=[
                ('superkey', models.CharField(default=None, max_length=100)),
                ('employee_id', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('fname', models.CharField(default=None, max_length=20)),
                ('mname', models.CharField(default=None, max_length=20, null=True)),
                ('lname', models.CharField(default=None, max_length=20)),
                ('picture', models.ImageField(blank=True, default='profile_pic/profile_picture.jpg', upload_to='profile_pic/')),
                ('designation', models.CharField(default=None, max_length=50)),
                ('salary', models.IntegerField(default=0)),
                ('dob', models.DateField(default=None)),
                ('phone', models.CharField(default=None, max_length=13)),
                ('emailid', models.EmailField(default=None, max_length=100)),
                ('address', models.CharField(default=None, max_length=200)),
                ('state', models.CharField(default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=50)),
                ('pincode', models.CharField(default=None, max_length=10)),
                ('father_name', models.CharField(default=None, max_length=60)),
                ('father_phone', models.CharField(default=None, max_length=13, null=True)),
                ('mother_name', models.CharField(default=None, max_length=60)),
                ('mother_phone', models.CharField(default=None, max_length=13, null=True)),
                ('from_date', models.DateField(default=None)),
                ('to_date', models.DateField(default=None, null=True)),
            ],
            options={
                'verbose_name': "Hotel Employee's Detail",
            },
        ),
        migrations.CreateModel(
            name='Hotel_Management',
            fields=[
                ('mainkey', models.CharField(default=None, max_length=100)),
                ('superkey', models.CharField(default=None, max_length=100, unique=True)),
                ('registration_no', models.CharField(default=None, max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(default=None, max_length=20, unique=True)),
                ('password', models.CharField(default=None, max_length=20)),
                ('emailid', models.EmailField(default=None, max_length=100)),
                ('phone', models.CharField(default=None, max_length=10)),
                ('hotel_name', models.CharField(default=None, max_length=50)),
                ('state', models.CharField(default=None, max_length=30)),
                ('city', models.CharField(default=None, max_length=30)),
                ('pincode', models.CharField(default=None, max_length=6)),
                ('address', models.CharField(default=None, max_length=200)),
            ],
            options={
                'verbose_name': "Hotel's Detail",
            },
        ),
        migrations.CreateModel(
            name='Hotel_Room_Register',
            fields=[
                ('superkey', models.CharField(default=None, max_length=100)),
                ('room_id', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('room_no', models.CharField(default=None, max_length=20)),
                ('room_type', models.CharField(default=None, max_length=100)),
                ('ac', models.BooleanField(blank=True, default=False, null=True)),
                ('room_cost', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Hotel Room's Detail",
            },
        ),
    ]
